---

  - name: Atualiza os repositorios
    apt:
      name: "*"
      state: latest
      update_cache: yes

  - name: Instalando os pacotes do docker
    apt: 
      name: 
        - apt-transport-https
        - ca-certificates 
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true 

  - name: Adicionar a chave
    apt_key:
      state: present 
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg" 
      
  - name: Adicionar o repositório a lista de sources.list
    apt_repository: 
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      filename: docker 

  - name: Instalando o docker
    apt:
      name:  
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: true

# - name: Inserindo o usuário de deployment no grupo do docker
#   user:
#     name: deployment
#     append: yes
#     groups:
#       - deployment
#       - docker
#     state: present

...
